#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🕺 Permorming linting checks..."
yarn run lint
echo "Your code is beatiful, nice job 👍"

echo "🧪 Testing your ugly code..."
yarn run test
echo "All tests passed 🚀"