#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🕺 Permorming linting checks..."
npm run lint
echo "Your code is beatiful, nice job 👍"

echo "🧪 Testing your ugly code..."
npm run test
echo "All tests passed 🚀"