name: Develop
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Intall dependencies
        run: yarn install

      - name: Compile smart contract
        run: yarn compile

      - name: Run linting checks
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Run static analysis with slither
        uses: crytic/slither-action@main
        id: slither
        continue-on-error: true
        with:
          sarif: results.sarif

      - name: Upload static anaylisis SARIF output file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}